---
- name: restart unifi
  service:
    name: "unifi"
    state: restarted
  become: yes
  tags: unifi-controller

- name: restart mongodb
  service:
    name: "mongodb"
    state: restarted
  become: yes
  tags: unifi-controller
